Update input width in _chips.scss sass component
Dogfalo/materialize pull request #6567
Opened 2020-06-05 11:28 UTC by Git-Harshit

This is a minor but suitable change which updates the width of input field (for adding new chips) from fixed 120px to fit-content, with same !important weight. Also, the min-width and max-width properties are set to limit its size between 100px and 200px. With this change, the input placeholder (if limited to under 200px) will not get cropped, and it will also have a better fit into the input field.

## Proposed changes

Basically, this change fixes the issue that I had encountered recently with the placeholder or text of the input before pressing enter to convert it to a chip. Please have a look at how this small change affects the chips input (Screenshot from Google Chrome):
![Capture-ChangePropose](https://user-images.githubusercontent.com/57865187/83871438-ac1b1d80-a74d-11ea-97ca-673b94d78ad7.PNG)

## Screenshots (if appropriate) or codepen:

## Types of changes

- [ x ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [ x ] I have read the **[CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-07-10 19:05 UTC, DanielRuf requested changes
Attention, this will not work on IE11. We should keep the old rule and add the new rule after it. So browsers who support it will use the second width rule.

https://caniuse.com/#feat=mdn-css_properties_width_fit-content

2020-07-10 20:50 UTC, Git-Harshit commented
Yes @DanielRuf sir! Thank you for mentioning! It did actually slip out of my mind when I had made this pull request. I think even the default 'auto' value for width property might not work in the desired way for IE.
Also, can you please tell if the _!important_ weight is really necessary to be used here, as I don't think it is required for the width changes to take effect? 

Now, I guess it's time to update this PR.

2020-07-10 22:16 UTC, DanielRuf commented
Regarding the new or old width setting? !important is bad in general.

2020-07-11 12:17 UTC, Git-Harshit commented
> Regarding the new or old width setting? !important is bad in general.

Actually, it was about the old width setting, as there was *!important* used with `width:120px` CSS. Completely agreed, it isn't a good practice to use !important weight in general. 

Still, as it was used in the previous code, I didn't remove it for now. Please let me know if in case it has to be discarded.

2020-07-12 11:14 UTC, DanielRuf approved these changes
LGTM

2025-01-14 09:09 UTC, closed without merging